config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
   resources :users do
    member do
      get :following, :followers
    end
  end

    resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
scope "(:locale)" do
      resources :users
      
      get ':path', to: 'static_pages#show'
      get '*path', to: 'static_pages#show', as: :pages
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :page
  def home
    if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end
  
  def contact
  end

  private
  def page
    if(params.has_key?(:page))
      page='static_pages/'+params[:page]
    else
      page='static_pages/home'
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title,"About") %>
<h1>About</h1>
<p>
  The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide( :title,"Help") %>
<h1><%= t(:Help) %></h1>

<p>
  <p>Rebuilding any engine is no easy task. The reason for your rebuild can range from refreshing an engine with hundreds of thousands of miles, to wanting to extract every bit of performance, and everything in between. The information provided here can serve as a reference to not only familiarize yourself with the Honda B-Series engine, but also give you the foundation you need for your rebuild.</p>
<p>To start, we can look back to the 1986&ndash;1987 Prelude 2.0Si and the 1986&ndash;1989 Honda Vigor and Accord, where the B20A engine was first introduced in Japan. While many different variants of the B20A evolved from 1987&ndash;1991 in the Honda Prelude, the basis for that engine was very different than the popular B16/B17/B18 family. Our main focus here is on the B16/B18 family, where many of the popular B-Series parts (OEM and aftermarket) are interchangeable. Honda reintroduced the B20B and B20Z in the first-generation Honda CR-V (1996). This generation of the B20B and B20Z was designed more similar to the B16/B18 family, and to the enthusiasts&rsquo; development of the B20/VTEC engine. The B20B and B20Z shared similar traits with the popular B16/B18 series.</p>
<p>The B-Series engines have become the most coveted Honda engines due to their reliability and the ability to produce high horsepower relative to their displacement. They are also readily available and can be found reasonably priced. The major benefit of the B-Series engine is also the ability to be transplanted into various Honda chassis, such as the Honda Civic.</p>
<p><strong>The B16 Family</strong></p>
<p>The Honda B16 has appeared in six different forms over the years. To identify any B-Series engine, the letter B is normally followed by two numbers&mdash;which designates the displacement of the engine&mdash;another letter and in the case of US-spec engines, a final number. The Japanese-spec engines normally have a four-digit alphanumerical designation. The B16A was first found in the 1989&ndash;1993 Japanese-spec Honda Integra RSi and XSi vehicles. It was also placed in the 1989&ndash;1991 Japanese-spec Honda CRX SiR and Honda Civic SiR/SiRII. The first generation of B16As was a 16-valve 4-cylinder with a displacement of 1595 cc, or just under 1.6L. Sporting a 10.2:1 compression ratio, it put out 158 hp @ 7,600 rpm along with 112 ft-lbs of torque @ 7,000 rpm. This first generation of DOHC VTEC technology from Honda formed the basis for the ever-popular B-Series engine.</p>
<p><img src="https://www.cartechbooks.com/media/wysiwyg/techtips/hondabseries/SA154-1-1.jpg" alt="b16aingsr" width="600" />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;<strong><em>&nbsp;Here is&nbsp;of the rare occasions you&rsquo;ll actually see a B16A in a third-generation Integra GS-R. The owner of this vehicle actually blew his factory B18C and replaced it with a cheaper first-generation JDM (Japanese Domestic Market) B16A.</em></strong></p>
<p>From 1992&ndash;1995, the Japanese-market B16A was seen in the Honda Civic SiR/SiRII chassis with a horsepower increase due to a slightly higher 10.4:1 compression ratio. A variant of that generation B16A&nbsp; was also seen in the 1992&ndash;1995 Honda Civic VTi in Europe and the&nbsp;&nbsp; Honda CRX del Sol SiR. These engines still had the 10.4:1 compression ratio and ranged in horsepower from 158 to 170.</p>
<p>The B16A1 variant can be found in the European-spec Honda CRX and Honda Civic from 1989&ndash;1991. It had a 1,595-cc displacement, 10.2:1 compression ratio, and 160 hp. The first time the B16-series set foot on American soil was in the B16A3-powered 1994&ndash;1995 Honda del Sol. Its specs varied slightly from the existing B16As, keeping the 1595-cc displacement, but bumping to a 10.4:1 compression ratio and an output rating of 160 hp @ 7,800 rpm and 111 ft-lbs of torque @ 7,000 rpm. With its 8,200-rpm redline, the B16A3 became the envy of many Honda owners.</p>
<p>The more popular B16A2 was spotted in the 1996&ndash;1997 Honda del Sol and in 1999&ndash;2000 when Honda reintroduced the Civic Si in a coupe form. Sporting the same 160-hp rating and 1.6L displacement, the popular B16A2 was a nice fit to the Civic coupe. The B16A2 was&nbsp;&nbsp; also seen in the European-spec 1992&ndash;2000 Honda Civic VTi.</p>
<p><em><strong>&nbsp;The 1999&nbsp;</strong><strong>Civic Si came with a B16A2 engine and was a huge hit with Honda enthusiasts nationwide. It was the first time the Civic chassis (other than the del Sol) came with a B-Series from the factory in the United States.</strong></em></p>
<p>Less commonly spoken about or even seen is the B16A6, found in the 1996&ndash;2000 Honda Civic in South Africa. Lastly, the infamous B16B was found in the extremely rare Japanese-spec Civic Type-R. This 1.6L sported a high 10.8:1 compression ratio and put out 185 hp @ 8,200 rpm and 118 ft-lbs of torque @ 7,500 rpm. To this day, the B16B stands out as a highly sought after swap.</p>
<p>&nbsp;</p>
<p><strong>The B17 Family</strong></p>
<p>The B17-Series was actually fairly uncommon and was only seen in the 1992&ndash;1993 Integra GS-R. This 1.7L put out 170 hp @ 7,600 rpm and 117 ft-lbs of torque @ 8,000 rpm. You don&rsquo;t come across one of these very often. If you are one of those lucky owners looking to rebuild a B17-series powerplant, do not fear! The same rebuild methods and procedures apply to this engine as well.</p>
<p><strong>The B18 Family</strong></p>
<p>The B18s are arguably the most popular members of the B-Series family. The B18 came in both non-VTEC and VTEC variations. The B18A non-VTEC powerplant was first seen in the 1986&ndash;1989 Accord Aerodeck, EXL-S/EX-S, and Vigor MXL-S in Japan. It was a 1.8L that made 160 hp and 128 ft-lbs of torque with dual Keihin carburetors. The B18A is hardly (if ever) seen stateside and are essentially a destroked version of the Honda B20A engine mentioned previously.</p>
<p>The first B18 engine seen stateside was the B18A1 in the 1990&ndash;1993 Acura Integra RS/LS/GS. It was a non-VTEC 1.8L motor that put out 130 hp from 1990&ndash;1991, while the 1992&ndash;1993 version had a slight increase to 140 hp. The beauty of the 1.8L powerplant, however, was its 121 ft-lbs of torque. The B18A1 was then updated to a B18B1 that was found in the 1994&ndash;2001 Acura Integra RS/LS/GS bodies. The B18B1 became a popular engine swap candidate, often referred as an &ldquo;LS swap&rdquo; among Honda enthusiasts. The 1.8L made 142 hp and 127 ft-lbs of torque, but also became a donor for the LS/VTEC swap that became popular later on.</p>
<p><img src="https://www.cartechbooks.com/media/wysiwyg/techtips/hondabseries/SA154-1-5.jpg" alt="b18bls" width="600" />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<em><strong>Here is a B18B LS engine. Notice the difference in the valve cover (it is not equipped with VTEC) compared to the VTEC&nbsp;B-Series engines.</strong></em></p>
<p>The most sought after and arguably the most popular B-Series engine comes from the B18C family. The B18C engine inherits the best of all the B-Series has to offer, with a 1.8L displacement and DOHC VTEC technology. The B18C could be found in many different variations, similar to the B16A where the Japanese-spec engines were simply B18C, while the American-spec were B18C1s in the GS-R and B18C5s in the Type-R. Versions of the Japanese-spec B18C were found in both the popular Integra Si-R and Type-R. While there was no way to differentiate between the two engines, the Type-R B18C built 197 hp compared to the Si-R version&rsquo;s 178 hp.</p>
<p>The US-spec B18C1 came from the factory in the Acura Integra GS-R model and sported 170 hp @ 7,600 rpm with 128 ft-lbs of torque. In 1997, the Type-R was introduced stateside and the USA-spec B18C5 made 195 hp @ 8,000 rpm and 130 ft-lbs of torque.</p>
<p><img src="https://www.cartechbooks.com/media/wysiwyg/techtips/hondabseries/SA154-1-3.jpg" alt="1999civicsi" width="600" />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;<em><strong>This 1999 Civic Si had the factory B16A2 replaced with a monster LS/VTEC setup. Though it looks stock, the LS block has actually been rebuilt with Type-R pistons and topped with a Type-R head. This engine setup with basic bolt-ons and tuning put down 200 reliable horsepower to the tires!</strong></em></p>
<p><em><strong><img src="https://www.cartechbooks.com/media/wysiwyg/techtips/hondabseries/SA154-1-6.jpg" alt="b18c5" width="600" />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;This is a genuine B18C5 Type-R engine in a USDM Integra Type-R. These are becoming more and more rare each day.</strong></em></p>
<p><em><strong><img src="https://www.cartechbooks.com/media/wysiwyg/techtips/hondabseries/SA154-1-4.jpg" alt="lsvtec" width="500" />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;This is a completely new LS/VTEC B-Series engine. This &ldquo;hybrid&rdquo; engine never came as original equipment in any Honda or Acura vehicle, but horsepower junkies in search of an edge can come with some very creative combinations.</strong></em></p>
<p><em><strong><img src="https://www.cartechbooks.com/media/wysiwyg/techtips/hondabseries/SA154-1-7.jpg" alt="civicsinotenough" width="600" />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Here is a 1999 Civic Si equipped with a complete B18C5 Type-R engine. The owner of this vehicle decided that the B16A2 wasn&rsquo;t enough for him, and with all the hype of the B18C5 Type-R engine, he purchased one and transplanted it into his car.<br /><br /></strong></em></p>
<p><strong>The B20 Family</strong></p>
<p>While the B20 was not popular at first, once LS/VTEC swaps became popular, many enthusiasts pushed the envelope, using the B20 as the bottom end for their &ldquo;Frankenstein&rdquo; swaps. By combining the bottom end of the 2.0L and the head of a VTEC B-Series version, many enthusiasts were able to extract plenty of torque and high-end horsepower for their Hondas.</p>
<p>The B20A3 and B20A5 were first seen in the 1990&ndash;1991 Prelude S and Si models, sporting 104 hp and 135 hp, respectively. The B20B found in the US-spec CR-V was seen in the 1997-up models, sporting 126 hp and 133 ft-lbs of torque.</p>
<p>The B20B was also seen in Japan from 1995&ndash;1998, but it was similar to the USA-spec B20B. In 1999&ndash;2000, however, the JDM B20B utilized higher compression pistons and was rated at 146 hp. In 1999&ndash;2000, the US version of the JDM B20B became known as the B20Z, sporting the same 146 hp.</p>
<p><strong>OBD Differences</strong></p>
<p>OBD stands for On-Board Diagnostics. When people distinguish between OBD1 or OBD2, they are referring to the generation of diagnostics system contained the ECU for your B-Series engine. If you&rsquo;re wondering which OBD generation your engine is equipped with, there is a general rule to follow for the B-Series application: pre-1991 engines utilize OBD0, while OBD1 was used from 1992&ndash;1995. OBD2 was used from 1996&ndash;1999, and from 1999&ndash;2004, the Civic Si and various models of the Integra came with OBD2.</p>
<p><strong>Japanese-Spec B-Series Engines</strong></p>
<p>The most valued and rare Japanese B-Series engines &nbsp;are the B16B and the B18C Type-R, found in the Civic Type-R and Integra Type-R, respectively. We were fortunate enough to capture photos of completely stock Japanese-spec Civic Type-Rs and Integra Type-Rs.</p>
<p>With the exception of the 1999&ndash;2000 Civic Si, the U.S. market was never fortunate enough to have a B-Series straight from the factory in a Civic. In Japan however, the B16A was extremely popular due to the fact that it came factory in the Civic.</p>
<p><img src="https://www.cartechbooks.com/media/wysiwyg/techtips/hondabseries/SA154-SB1-1-1.jpg" alt="genuinejdm" width="600" />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;<em><strong>This is a genuine JDM B16B housed in an authentic Japanese Civic Type-R. The B16B is extremely rare stateside and you&rsquo;ll run into Honda enthusiasts who aren&rsquo;t huge fans of them since they still carry the 1.6L displacement. (Photo courtesy Ken Williams)</strong></em></p>
<p><em><strong><img src="https://www.cartechbooks.com/media/wysiwyg/techtips/hondabseries/SA154-SB1-1-2.jpg" alt="jdmb18c" width="600" />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;This is a genuine JDM B18C in a stock Integra Type-R in Japan. This motor is heavily sought after on the stateside and some Honda enthusiasts will argue that it is the best B-Series ever produced from the factory. The JDM B18C also came equipped with its own JDM 4-1 header, which is very popular amongst Honda enthusiasts as a great performance bolt-on. (Photo courtesy Ken Williams)</strong></em></p>
<p><em><strong><img src="https://www.cartechbooks.com/media/wysiwyg/techtips/hondabseries/SA154-SB1-1-4.jpg" alt="civiceg" width="600" />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Many of the 1992&ndash;1995 Civic EG chassis in Japan came equipped with a B16A from the factory. Stateside enthusiasts weren&rsquo;t so lucky. (Photo courtesy Ken Williams)</strong></em></p>
<p><em><strong><img src="https://www.cartechbooks.com/media/wysiwyg/techtips/hondabseries/SA154-SB1-1-3.jpg" alt="jdmspec" width="600" />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;For those looking to import an engine from Japan, getting one of the JDM-spec B-Series engines is as easy as calling one of your local engine Honda distributors. You can search the Internet for a reputable source, but we of course recommend Plan B Motorsports. This is a photo of a JDM B18C that Plan B imported in from Japan.</strong></em></p>
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
            <section class="stats">
        <%= render 'shared/stats' %>
      </section>

      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
       
      </section>
      
    </aside>
    <div class="col-md-8">
      <h3><%= t(:Micropost_Feed) %></h3>
      <%= render 'shared/feed' %>
      

    </div>

  </div>
<% else %>
  <div class="center jumbotron">
    <h1> <%= t (:Welcome_to_the_Automobiles) %></h1>

    <h2>
      This is the home page for the
      <a href="https://www.autocarindia.com/">Autocar</a>
      sample application.
    </h2>

    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>
<h1><%=t :hello %></h1>
    <p><%= flash[:notice] %></p>
    <p><%= l Time.now, format: :short %></p>
  <%= link_to image_tag("autocar-logo.png", alt: "Rails logo"),
              'https://www.autocarindia.com/' %>
<% end %>