config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
   resources :users do
    member do
      get :following, :followers
    end
  end

    resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
scope "(:locale)" do
      resources :users
      
      get ':path', to: 'static_pages#show'
      get '*path', to: 'static_pages#show', as: :pages
    end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.powerdrift.com/videos-2/"> Tutorial</a>
    by <a href="http://www.powerdrift.com/">power drift</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to t(:About),  about_path %></li>
      <li><%= link_to t(:Contact), contact_path %></li>
      <li><a href="https://www.autocarindia.com/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t(:Automobiles), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t(:Home), root_path %></li>
        <li><%= link_to t(:Help), help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t(:Log_in), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <nav>
      <div class="menu" lang = <%= I18n.locale %> dir= <%= @local_dir %> >
        <ul class="vertical menu">
          <li><%= t('languages.languages') %>:
              <%= link_to t('languages.en'), root_path(locale: 'en') %> 
              <%= link_to t('languages.fa'), root_path(locale: 'fa') %>
              <%= link_to t('languages.ne'), root_path(locale: 'ne') %>
              <%= link_to t('languages.th'), root_path(locale: 'th') %>
              <hr />
          </li>
         
        </ul>
      </div>
    </nav>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>